library(sqldf)
gap <- read.csv.sql("../Documents/household_power_consumption.txt", sql = "select Global_active_power from file where Date = '1/2/2007' or Date = '2/2/2007'", header = TRUE, sep = ";")
png("plot1.png", width = 480, height = 480)
with(gap, hist(Global_active_power, col = 'red', main = "Global Active Power", xlab = "Global Active Power (kilowatts)"))
dev.off()