library(sqldf)
esm <- read.csv.sql("../Documents/household_power_consumption.txt", sql = "select Date, Time, Sub_metering_1, Sub_metering_2, Sub_metering_3 from file where Date = '1/2/2007' or Date = '2/2/2007'", header = TRUE, sep = ";")
x_axis <- with(esm, strptime(paste(as.Date(Date,"%d/%m/%Y"),Time),"%Y-%m-%d %H:%M:%S"))
png("plot3.png", width = 480, height = 480)
plot(x_axis, esm$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "", col = "black")
lines(x_axis, esm$Sub_metering_2, col = "red")
lines(x_axis, esm$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = 1, col=c("black","red","blue"))
dev.off()